"""initial migration

Revision ID: 0001
Revises: 
Create Date: 2020-07-15 23:07:36.957705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_users_email"), "auth_users", ["email"], unique=True)
    op.create_table(
        "auth_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("is_applied", sa.Boolean(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["auth_users.id"]),  # noqa
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"]),  # noqa
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_auth_invites_token"), "auth_invites", ["token"], unique=True)
    op.create_table(
        "podcast_podcasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("publish_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("download_automatically", sa.Boolean(), nullable=True),
        sa.Column("rss_link", sa.String(length=128), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["auth_users.id"]),  # noqa
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publish_id"),
    )
    op.create_table(
        "podcast_episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("podcast_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("watch_url", sa.String(length=128), nullable=True),
        sa.Column("remote_url", sa.String(length=128), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(length=128), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["auth_users.id"]),  # noqa
        sa.ForeignKeyConstraint(["podcast_id"], ["podcast_podcasts.id"]),  # noqa
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_podcast_episodes_created_by_id"),
        "podcast_episodes",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_podcast_episodes_podcast_id"), "podcast_episodes", ["podcast_id"], unique=False
    )
    op.create_index(
        op.f("ix_podcast_episodes_source_id"), "podcast_episodes", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_podcast_episodes_source_id"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_podcast_id"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_created_by_id"), table_name="podcast_episodes")
    op.drop_table("podcast_episodes")
    op.drop_table("podcast_podcasts")
    op.drop_index(op.f("ix_auth_invites_token"), table_name="auth_invites")
    op.drop_table("auth_invites")
    op.drop_index(op.f("ix_auth_users_email"), table_name="auth_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
