"""episode_source

Revision ID: 0006
Revises: 0005
Create Date: 2021-10-17 18:51:29.927189

"""

import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String
from alembic import op

# revision identifiers, used by Alembic.
revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


episodes = table("podcast_episodes", column("source_type", String))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("podcast_episodes", sa.Column("source_type", sa.VARCHAR(16), nullable=True))
    op.execute(episodes.update().values({"source_type": "YOUTUBE"}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("podcast_episodes", "source_type")
    # ### end Alembic commands ###
