"""File: added public

Revision ID: 0013
Revises: 0012
Create Date: 2022-06-02 22:32:02.254358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_files",
        sa.Column("public", sa.Boolean, nullable=False, default=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_files", "public")
    # ### end Alembic commands ###
