"""EnumFields: make as postgres enum

Revision ID: 0017
Revises: 0016
Create Date: 2023-01-24 09:21:16.226588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def change_to_upper(table: str, field_name: str):
    bind = op.get_bind()
    query = f"""
        UPDATE {table}
        SET {field_name} = UPPER({field_name}) WHERE {field_name} IS NOT NULL 
    """
    bind.execute(text(query))


def change_to_lower(table: str, field_name: str):
    bind = op.get_bind()
    query = f"""
        UPDATE {table}
        SET {field_name} = LOWER({field_name}) WHERE {field_name} IS NOT NULL 
    """
    bind.execute(text(query))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    change_to_upper(table="media_files", field_name="type")
    change_to_upper(table="podcast_cookies", field_name="source_type")
    change_to_upper(table="podcast_episodes", field_name="source_type")
    change_to_upper(table="podcast_episodes", field_name="status")

    media_files__file_type = postgresql.ENUM("AUDIO", "IMAGE", "RSS", name="media_files__file_type")
    media_files__file_type.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "media_files",
        "type",
        existing_type=sa.VARCHAR(length=16),
        type_=media_files__file_type,
        existing_nullable=False,
    )
    op.alter_column(
        "podcast_cookies",
        "source_type",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="cookies__source_type"),
        nullable=False,
    )
    op.alter_column(
        "podcast_episodes",
        "source_type",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="episodes__source_type"),
        nullable=False,
    )
    op.alter_column(
        "podcast_episodes",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "NEW", "DOWNLOADING", "PUBLISHED", "ARCHIVED", "ERROR", name="episodes__episode_status"
        ),
        existing_nullable=False,
    )
    op.drop_constraint("podcast_episodes_podcast_id_fkey", "podcast_episodes", type_="foreignkey")
    op.create_foreign_key(
        "podcast_episodes_podcast_id_fkey",
        "podcast_episodes",
        "podcast_podcasts",
        ["podcast_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("podcast_episodes_podcast_id_fkey", "podcast_episodes", type_="foreignkey")
    op.create_foreign_key(
        "podcast_episodes_podcast_id_fkey",
        "podcast_episodes",
        "podcast_podcasts",
        ["podcast_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "podcast_episodes",
        "status",
        existing_type=sa.Enum(
            "NEW", "DOWNLOADING", "PUBLISHED", "ARCHIVED", "ERROR", name="episodes__episode_status"
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "podcast_episodes",
        "source_type",
        existing_type=sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="episodes__source_type"),
        type_=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.alter_column(
        "podcast_cookies",
        "source_type",
        existing_type=sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="cookies__source_type"),
        type_=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.alter_column(
        "media_files",
        "type",
        existing_type=sa.Enum("AUDIO", "IMAGE", "RSS", name="media_files__file_type"),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    # todo: drop enums

    change_to_upper(table="media_files", field_name="type")
    change_to_upper(table="podcast_cookies", field_name="source_type")
    change_to_upper(table="podcast_episodes", field_name="source_type")
    change_to_upper(table="podcast_episodes", field_name="status")
    # ### end Alembic commands ###
