"""Files: added meta field

Revision ID: 6f97ecebbf04
Revises: 8c907f32fe37
Create Date: 2022-07-21 09:20:01.998052

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6f97ecebbf04"
down_revision = "8c907f32fe37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_files",
        sa.Column("hash", sa.String(length=64), nullable=False, default=""),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_files", "meta")
    # TODO: replace with
    # op.drop_column("media_files", "hash")
    # ### end Alembic commands ###
