"""Episodes on-delete relation

Revision ID: e10362dc785b
Revises: 9590cd1e3aa7
Create Date: 2020-11-25 09:39:29.322135

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e10362dc785b'
down_revision = '9590cd1e3aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('podcast_episodes_podcast_id_fkey', 'podcast_episodes', type_='foreignkey')
    op.create_foreign_key(None, 'podcast_episodes', 'podcast_podcasts', ['podcast_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcast_episodes', type_='foreignkey')
    op.create_foreign_key('podcast_episodes_podcast_id_fkey', 'podcast_episodes', 'podcast_podcasts', ['podcast_id'], ['id'])
    # ### end Alembic commands ###
