"""auth_sessions

Revision ID: e7ecd1af5d35
Revises: e10362dc785b
Create Date: 2021-06-16 08:23:20.721662

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e7ecd1af5d35"
down_revision = "e10362dc785b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from auth_sessions where 1;")
    op.add_column("auth_sessions", sa.Column("public_id", sa.String(length=36), nullable=False))
    op.alter_column("auth_sessions", "last_login", new_column_name="refreshed_at")
    op.alter_column(
        "auth_sessions",
        "refresh_token",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=512),
    )
    op.alter_column(
        "auth_sessions",
        "refresh_token",
    )
    op.create_index(op.f("ix_auth_sessions_public_id"), "auth_sessions", ["public_id"], unique=True)
    op.drop_constraint("auth_sessions_user_id_key", "auth_sessions", type_="unique")
    # op.drop_column('auth_sessions', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("auth_sessions", "refreshed_at", new_column_name="last_login")
    op.alter_column(
        "auth_sessions",
        "refresh_token",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=256),
    )
    op.create_unique_constraint("auth_sessions_user_id_key", "auth_sessions", ["user_id"])
    op.drop_index(op.f("ix_auth_sessions_public_id"), table_name="auth_sessions")
    op.drop_column("auth_sessions", "public_id")
    # ### end Alembic commands ###
