"""Rename: source_id -> remote_id

Revision ID: ee5e52edb083
Revises: d6fcd3132857
Create Date: 2022-01-18 09:52:02.545614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5e52edb083'
down_revision = 'd6fcd3132857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_episodes', column_name='source_id', new_column_name='remote_id')
    op.drop_index('ix_podcast_episodes_source_id', table_name='podcast_episodes')
    op.create_index(op.f('ix_podcast_episodes_remote_id'), 'podcast_episodes', ['remote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_episodes', column_name='remote_id', new_column_name='source_id')
    op.drop_index(op.f('ix_podcast_episodes_remote_id'), table_name='podcast_episodes')
    op.create_index('ix_podcast_episodes_source_id', 'podcast_episodes', ['source_id'], unique=False)
    # ### end Alembic commands ###
