version: '3'
services:
  web:
    image:
      ${REGISTRY_URL}/podcast-service:last
    env_file:
      - .env
    environment:
      - APP_SERVICE=web
    ports:
      - 127.0.0.1:${APP_PORT}:8000
    networks:
      - podcast-subnet

  rq:
    image:
      ${REGISTRY_URL}/podcast-service:last
    env_file:
      - .env
    environment:
      - APP_SERVICE=rq
    networks:
      - podcast-subnet

  migrate_db:
    image:
      ${REGISTRY_URL}/podcast-service:last
    env_file:
      - .env
    environment:
      - APP_SERVICE=migrate_db
    networks:
      - podcast-subnet

networks:
  internal-subnet:
    external: true
