name: Deploy Application
on:
  push:
    branches:
      - master
      - feature/issue-19-cd-build-and-deploy

jobs:
#  test:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:11
#        env:
#          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
#          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
#          POSTGRES_DB: ${{ secrets.DB_NAME }}
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Prepare .env file
#        env:
#          DB_NAME: ${{ secrets.DB_NAME }}
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#          DB_HOST: ${{ secrets.DB_HOST }}
#          DB_PORT: ${{ secrets.DB_PORT }}
#        run: |
#          cp .env.template .env
#          env >> .env
#
#      - name: Build image
#        run: docker-compose build test
#        env:
#          PYPI_USER: ${{ secrets.PYPI_USER }}
#          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#
#      - name: Create docker-subnet
#        run: docker network create podcast-subnet
#
#      - name: Run tests
#        run: docker-compose up --exit-code-from test test

  build-and-deploy:
#    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Docker login
        run: |
          echo ${{ secrets.GH_PACK_KEY }} | docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

#      - name: Build image
#        run: docker build -t ${{ secrets.GH_PACK_URL }} -f Dockerfile .
#
#      - name: Push image to registry
#        run: docker push ${{ secrets.GH_PACK_URL }}

#      - name: Prepare SSH key
#        run: |
#          echo ${{ secrets.SSH_PKEY }} > /home/runner/.ssh/id_rsa
#          chmod 400 /home/runner/.ssh/id_rsa
#
      - name: Copy docker-compose.yaml
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PKEY }}
          SOURCE: "./docker-compose.yaml"
          REMOTE_HOST: ${{ secrets.PROD_SSH_HOST }}
          REMOTE_USER: ${{ secrets.PROD_SSH_PORT }}
          TARGET: ${{ secrets.PROD_PROJECT_ROOT }}/docker-compose.yaml

#      - name: Copy docker compose file
#        run: |
#          scp -v -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa ./docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_PROJECT_ROOT }}/docker-compose.yaml

      - name: SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PKEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.GH_PACK_URL }}


#      - name: Docker login
#        run: |
#          docker login https://docker.pkg.github.com -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#
#      - name: Build image
#        run: |
#          docker build -t docker.pkg.github.com/procruteam/podcast-service/podcast-service:last -f Dockerfile .
#
#      - name: Push image to docker.io
#        run: |
#          docker push docker.pkg.github.com/procruteam/podcast-service/podcast-service:last
